README.md
build.gradle.kts

Issue #2: Add Gradle Task to generate Usage Documentation

Issue #2: Add Gradle Task to generate Usage Documentation

---

build.gradle.kts

This is the POM that it'll be generated
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<modelVersion>4.0.0</modelVersion>
<groupId>com.cjbooms</groupId>
<artifactId>fabrikt</artifactId>
<version>1.0.0</version>
<name>Fabrikt</name>
<description>Fabricates Kotlin code from OpenApi3 specifications</description>
<url>https://github.com/cjbooms/fabrikt</url>
<inceptionYear>2020</inceptionYear>
<licenses>
<license>
<name>Apache License 2.0</name>
<url>https://opensource.org/licenses/Apache-2.0</url>
</license>
</licenses>
<developers>
<developer>
<id>cjbooms</id>
<name>Conor Gallaguer</name>
<email>cjbooms@gmail.com</email> …
```

Issue #3: Publish Lib to maven central

---

README.md
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGen.kt
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenArgs.kt
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/resources/examples/javaSerializableModels/models/Models.kt
src/test/resources/examples/javaSerializableModels/open-api/api.yaml

Add Java Serialization Option to Models

Issue #12: Add Java Serialization Option to Models

---

.github/workflows/build.yml
README.md
build.gradle.kts
gradle/wrapper/gradle-wrapper.properties
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/QuarkusReflectionModelGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/model/Destinations.kt
src/main/kotlin/com/cjbooms/fabrikt/model/GeneratedFiles.kt
src/main/kotlin/com/cjbooms/fabrikt/model/QuarkusReflectionModel.kt
src/main/kotlin/com/cjbooms/fabrikt/util/FileUtils.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ResourceGeneratorTest.kt
src/test/resources/examples/githubApi/resources/reflection-config.json
src/test/resources/examples/quarkusReflectionModels/api.yaml
src/test/resources/examples/quarkusReflectionModels/models/Models.kt

Issue #24 Add the ability to generate the quarkus reflection-config.jon file

Issue #24 Add the ability to generate the quarkus reflection-config.jon file

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/resources/examples/oneOfPolymorphicModels/api.yaml
src/test/resources/examples/oneOfPolymorphicModels/models/Models.kt

ISSUE #28  This was causing incorrect annotations to appear

Fixing the issue with identical discriminator names 

---

.github/workflows/publish.yml

Fixing Java version in Github publish action

Fixing Java version in Github publish action

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/resources/examples/externalReferences/external-models.yaml
src/test/resources/examples/externalReferences/models/Models.kt
src/test/resources/examples/githubApi/models/Models.kt
src/test/resources/examples/githubApi/resources/reflection-config.json

Fixes the issue where generation stops when an array element in an externally referenced schema is encountered

Improve external reference support

---

src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt
src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt
src/test/resources/examples/inLinedObject/api.yaml
src/test/resources/examples/inLinedObject/models/Models.kt

Issue #36: Generated class names are inconsistent for inline array objects

Issue #36: Generated class names are inconsistent for inline array objects

---

src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/controller/ControllerGeneratorUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/resources/examples/defaultValues/api.yaml
src/test/resources/examples/defaultValues/models/Models.kt

Issue #34: Optional properties with a default should not be nullable

Issue #34: Optional properties with a default should not be nullable

---

src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt
src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/resources/examples/polymorphicModels/api.yaml
src/test/resources/examples/polymorphicModels/sealed/models/Models.kt

Fixing bug with constructor when multiple objects under an allOf, but only one is the super class

Fixing bug with constructor when multiple objects under an allOf

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/model/KotlinGenModels.kt

When transitioning from Controller implementations to interfaces. There is a hole in our tests that doesn't pick this up, but it would be a time-consuming test to rejig

These static imports are important, they were accidentally removed 

---

build.gradle.kts
src/main/kotlin/com/cjbooms/fabrikt/generators/controller/ControllerGeneratorUtils.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/SpringControllerGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/util/ResourceHelper.kt
src/test/resources/examples/enumPolymorphicDiscriminator/models/Models.kt
src/test/resources/examples/githubApi/controllers/Controllers.kt
src/test/resources/examples/javaSerializableModels/models/Models.kt
src/test/resources/examples/okHttpClient/client/ApiClient.kt
src/test/resources/examples/okHttpClient/client/ApiService.kt
src/test/resources/examples/okHttpClient/models/Models.kt
src/test/resources/examples/oneOfPolymorphicModels/models/Models.kt
src/test/resources/examples/polymorphicModels/models/Models.kt
src/test/resources/examples/polymorphicModels/sealed/models/Models.kt
src/test/resources/examples/quarkusReflectionModels/models/Models.kt

Bump kotlin and ktlint versions

Bump kotlinand ktlint versions

---

src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpSimpleClientGenerator.kt
src/main/resources/templates/client-code/http-util.kt.hbs
src/test/resources/examples/okHttpClient/api.yaml
src/test/resources/examples/okHttpClient/client/ApiClient.kt
src/test/resources/examples/okHttpClient/client/ApiService.kt
src/test/resources/examples/okHttpClient/client/HttpUtil.kt

Support explode style query parameters which are the default

Support explode style query parameters which are the default

---

src/main/resources/templates/client-code/http-resilience4j-util.kt.hbs
src/main/resources/templates/client-code/logging-interceptor.kt.hbs
src/main/resources/templates/client-code/oauth.kt.hbs
src/test/resources/examples/okHttpClient/client/HttpResilience4jUtil.kt
src/test/resources/examples/okHttpClient/client/LoggingInterceptor.kt
src/test/resources/examples/okHttpClient/client/OAuth.kt

- Making the OAuth class a general purpose Interceptor and Authenticator that takes a token function
- Improving formatting of client classes

Improving client

---

src/main/resources/templates/client-code/oauth.kt.hbs

Adding missing import

---

src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt
src/main/kotlin/com/cjbooms/fabrikt/model/OasType.kt
src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt
src/test/resources/examples/githubApi/api.yaml
src/test/resources/examples/githubApi/controllers/Controllers.kt
src/test/resources/examples/optionalVsRequired/api.yaml
src/test/resources/examples/optionalVsRequired/models/Models.kt

Add support for the UUID format of strings

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt

ISSUE-60 Simplifying the capture of external document URLs

---

build.gradle.kts
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGen.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/OkHttpClientGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ResourceGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/SpringControllerGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/util/Linter.kt

It conflicts with the version of kotlin in source projects

ISSUE-60 Backing out linter entirely.

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt

ISSUE-60 Attempting to eliminate duplicates

ISSUE-60 Attempting to eliminate duplicates

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt

ISSUE-60 Attempting to eliminate duplicates coming from external API docs
#60

ISSUE-60 Attempting to eliminate duplicates coming from external API docs

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt

ISSUE-60 Capturing inlined oneOfs also

ISSUE-60 Capturing inlined oneOfs also

---

README.md
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/resources/examples/micronautIntrospectedModels/api.yaml
src/test/resources/examples/micronautIntrospectedModels/models/Models.kt

ISSUE-58: Add support for adding the Micronaut @Introspected annotation to the models

ISSUE-58: Add support for Micronaut @Introspected models

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt
src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt
src/test/resources/examples/mapExamples/api.yaml
src/test/resources/examples/mapExamples/models/Models.kt

Fixing an issue where complex nested maps definitions failed to generate correctly when referencing other typed objects in the OAS scheama. Test case expanded to cover this scenario

Fix typed map issue

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/resources/examples/externalReferences/models/Models.kt

Don't attempt to generate external schemas from current API document. Save generation for external document processing

ISSUE-60 More targeted capturing of external schemas.

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt

Encountered a Null Pointer Exception when testing 1.3.0 from the Sonatype staging repo in some Zalando projects

Fixing NPE experienced when testing 1.3.0 

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt

Improving code formatting in Model Generator class

Improving code formatting in Model Generator class

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt

Another attempt at fixing the NPE experienced with 1.3.0

Another attempt at fixing the NPE experienced with 1.3.0

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt

Removing warning log message.

---

src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpEnhancedClientGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpSimpleClientGenerator.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/OkHttpClientGeneratorTest.kt
src/test/resources/examples/okHttpClient/api.yaml
src/test/resources/examples/okHttpClient/client/ApiClient.kt
src/test/resources/examples/okHttpClientMultiMediaType/api.yaml
src/test/resources/examples/okHttpClientMultiMediaType/client/ApiClient.kt
src/test/resources/examples/okHttpClientMultiMediaType/client/ApiModels.kt
src/test/resources/examples/okHttpClientMultiMediaType/client/ApiService.kt
src/test/resources/examples/okHttpClientMultiMediaType/client/HttpResilience4jUtil.kt
src/test/resources/examples/okHttpClientMultiMediaType/client/HttpUtil.kt
src/test/resources/examples/okHttpClientMultiMediaType/client/LoggingInterceptor.kt
src/test/resources/examples/okHttpClientMultiMediaType/client/OAuth.kt
src/test/resources/examples/okHttpClientMultiMediaType/models/Models.kt

ISSUE-81: Accept header should be picked from the content response

ISSUE-81: Accept header should be picked from the content response

---

src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpEnhancedClientGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpSimpleClientGenerator.kt
src/test/resources/examples/okHttpClient/client/ApiClient.kt
src/test/resources/examples/okHttpClient/client/ApiService.kt
src/test/resources/examples/okHttpClientMultiMediaType/client/ApiClient.kt
src/test/resources/examples/okHttpClientMultiMediaType/client/ApiService.kt

This will be convenient for things like propagating Open-Tracing telemetry headers

Adding the ability to set arbitrary additional HTTP headers. 

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt

Seems to only happen when the open-source Zalando Problem schema was referenced at the very beginning of a document.
The fix is to validate the document URL's of external schemas and skip invalid ones

Fixing URL format exception 

---

src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpEnhancedClientGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpSimpleClientGenerator.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/OkHttpClientGeneratorTest.kt
src/test/resources/examples/okHttpClient/api.yaml
src/test/resources/examples/okHttpClientMultiMediaType/api.yaml
src/test/resources/examples/okHttpClientMultiMediaType/client/ApiClient.kt
src/test/resources/examples/okHttpClientMultiMediaType/client/ApiService.kt
src/test/resources/examples/okHttpClientMultiMediaType/models/Models.kt

Permitting the use of explicit Accept header in the generated clients

Permitting the use of explicit Accept header in the generated clients

---

build.gradle.kts
src/main/kotlin/com/cjbooms/fabrikt/util/YamlUtils.kt

Bump Kaizen parser to latest and improve error message when it throws a NPE

---

README.md
build.gradle.kts

https://issues.sonatype.org/browse/OSSRH-76255

Switch to new sonatype hosting infrastructure

---

README.md
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/resources/examples/micronautReflectionModels/api.yaml
src/test/resources/examples/micronautReflectionModels/models/Models.kt

ISSUE-101: Add Support for @ReflectiveAccess Micronaut annotations

ISSUE-101: Add Support for @ReflectiveAccess Micronaut annotations

---

src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/resources/examples/anyOfOneOfAllOf/models/Models.kt
src/test/resources/examples/arrays/models/Models.kt
src/test/resources/examples/deepNestedSharingReferences/models/Models.kt
src/test/resources/examples/duplicatePropertyHandling/models/Models.kt
src/test/resources/examples/enumExamples/models/Models.kt
src/test/resources/examples/enumPolymorphicDiscriminator/models/Models.kt
src/test/resources/examples/externalReferences/models/Models.kt
src/test/resources/examples/githubApi/models/Models.kt
src/test/resources/examples/inLinedObject/models/Models.kt
src/test/resources/examples/javaSerializableModels/models/Models.kt
src/test/resources/examples/mapExamples/models/Models.kt
src/test/resources/examples/micronautIntrospectedModels/models/Models.kt
src/test/resources/examples/micronautReflectionModels/models/Models.kt
src/test/resources/examples/oneOfPolymorphicModels/models/Models.kt
src/test/resources/examples/polymorphicModels/models/Models.kt
src/test/resources/examples/quarkusReflectionModels/models/Models.kt

This will aid comparison when the generation algorithm changes for #103 .

Alphabetically order generated test classes

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt
src/main/kotlin/com/cjbooms/fabrikt/model/OasType.kt
src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt
src/test/resources/examples/anyOfOneOfAllOf/api.yaml
src/test/resources/examples/anyOfOneOfAllOf/models/Models.kt

Support OpenApi3 Any type

---

README.md
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGen.kt
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenArgs.kt
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/MutableSettings.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/controller/SpringControllerInterfaceGenerator.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/OkHttpClientGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ResourceGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/SpringControllerGeneratorTest.kt

Add a `suspend_modifier` cli-option to add the `suspend` modifier to controller methods
Closes #112

Add cli option to add suspend modifier to controller methods

---

src/main/kotlin/com/cjbooms/fabrikt/model/OasType.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/resources/examples/anyOfOneOfAllOf/api.yaml
src/test/resources/examples/anyOfOneOfAllOf/models/Models.kt

Enable use of oneOf in additional properties

---

src/main/kotlin/com/cjbooms/fabrikt/model/SourceApi.kt
src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/SpringControllerGeneratorTest.kt
src/test/resources/examples/singleAllOf/api.yaml
src/test/resources/examples/singleAllOf/controllers/Controllers.kt
src/test/resources/examples/singleAllOf/models/Models.kt

Force type to be object if any properties are defined
Closes #121

Force type to be object if any properties are defined

---

README.md
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGen.kt
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenArgs.kt
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpClientGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpEnhancedClientGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpSimpleClientGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/model/Destinations.kt
src/main/kotlin/com/cjbooms/fabrikt/model/GeneratedFiles.kt
src/main/kotlin/com/cjbooms/fabrikt/model/HandlebarsTemplates.kt

Defaulting to `src/main/kotlin` causes issues with some Jetbrains plugins

Allow configuration of source and resources subdirectories.

---

build.gradle.kts

Switch back to mavenCentral now that jcenter has been discontinued

Remove jcenter repo.

---

src/main/kotlin/com/cjbooms/fabrikt/model/OasType.kt
src/test/resources/examples/anyOfOneOfAllOf/api.yaml
src/test/resources/examples/anyOfOneOfAllOf/models/Models.kt

Support oneOf of primitives.

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/resources/examples/enumPolymorphicDiscriminator/api.yaml

Fix casing issue in polymorphic Json Subtype resolution.
Closes #144

Fix casing issue in polymorphic Json Subtype resolution.

---

src/main/kotlin/com/cjbooms/fabrikt/generators/controller/SpringControllerInterfaceGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/controller/metadata/Spring.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/SpringControllerGeneratorTest.kt
src/test/resources/examples/springFormatDateAndDateTime/api.yaml
src/test/resources/examples/springFormatDateAndDateTime/controllers/Controllers.kt

Add spring controller datetimeformat annotations

---

src/test/resources/examples/anyOfOneOfAllOf/api.yaml
src/test/resources/examples/anyOfOneOfAllOf/models/Models.kt

Expand allOf permutation to validate required properties are inherited. Issue #128 suggests there is a problem here

Expand allOf permutation to validate required properties are inherited

---

src/main/kotlin/com/cjbooms/fabrikt/model/SourceApi.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/resources/examples/responsesSchema/api.yaml
src/test/resources/examples/responsesSchema/models/Models.kt

Resolving https://github.com/cjbooms/fabrikt/issues/156

Support responses schema

---

README.md
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/resources/examples/companionObject/api.yaml
src/test/resources/examples/companionObject/models/Models.kt

Include a model generator option to generate a companion object

---

build.gradle.kts
src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenArgs.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/OasDefault.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpSimpleClientGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/controller/SpringControllerInterfaceGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonMetadata.kt
src/main/kotlin/com/cjbooms/fabrikt/util/NormalisedString.kt

Migrate to Kotlin 1.6 and bump some libs.
Also adding some replacement functions for kotlin deprecations as the alternatives are ugly.

Kotlin 1 6

---

src/main/kotlin/com/cjbooms/fabrikt/generators/OasDefault.kt
src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt
src/main/kotlin/com/cjbooms/fabrikt/model/OasType.kt
src/test/resources/examples/defaultValues/api.yaml
src/test/resources/examples/defaultValues/models/Models.kt

Support byte arrays

---

src/main/kotlin/com/cjbooms/fabrikt/util/NormalisedString.kt
src/test/kotlin/com/cjbooms/fabrikt/util/NormalisedStringTest.kt

Not the prettiest, but this fixes #167

Support Norwegian characters

---

src/test/kotlin/com/cjbooms/fabrikt/util/NormalisedStringTest.kt

May as well pull the validation into primary test cases

remove dedicated norwegian tests

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/resources/examples/companionObject/api.yaml
src/test/resources/examples/companionObject/models/Models.kt

Add companion object on polymorphic subtypes
Closes #174

Add companion object on polymorphic subtypes

---

README.md
src/main/kotlin/com/cjbooms/fabrikt/generators/controller/MicronautControllerInterfaceGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/controller/SpringControllerInterfaceGenerator.kt

Update Readme with authentication controller option.

Update Readme with authentication controller option.

---

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt
src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt
src/test/resources/examples/nestedPolymorphicModels/api.yaml
src/test/resources/examples/nestedPolymorphicModels/models/Models.kt

Add support for generating nested polymorphic models 
Closes (#153)

Add support for generating nested polymorphic models (#153)

---

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/test/resources/examples/enumPolymorphicDiscriminator/api.yaml
src/test/resources/examples/polymorphicModels/api.yaml
src/test/resources/examples/polymorphicModels/models/Models.kt
src/test/resources/examples/polymorphicModels/sealed/models/Models.kt

Fixes snake case polymorphic schema names.

---

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt
src/test/resources/examples/enumPolymorphicDiscriminator/api.yaml
src/test/resources/examples/enumPolymorphicDiscriminator/models/Models.kt
src/test/resources/examples/polymorphicModels/api.yaml
src/test/resources/examples/polymorphicModels/models/Models.kt
src/test/resources/examples/polymorphicModels/sealed/models/Models.kt

Fixes Polymorphism with simple $ref schemas causes broken models #203

---

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt
src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt
src/test/resources/examples/arrays/api.yaml
src/test/resources/examples/arrays/models/Models.kt
src/test/resources/examples/enumExamples/api.yaml
src/test/resources/examples/enumExamples/models/Models.kt

Adds support  for top level array objects containing inlined items definitions.
Closes #188

Improve generation of inlined objects

---

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt
src/test/resources/examples/jsonMergePatch/api.yaml
src/test/resources/examples/jsonMergePatch/models/Models.kt

Sorry for the confusion. I think my last PR #208 was merged before it was tested properly.

Changed inner nullability of JsonNullable properties. Fixes #209

---

README.md
src/test/resources/examples/enumPolymorphicDiscriminator/api.yaml
src/test/resources/examples/enumPolymorphicDiscriminator/models/Models.kt

Update readme around polymorphic generation

Update readme around polymorphic generation

---

src/main/kotlin/com/cjbooms/fabrikt/generators/client/OpenFeignInterfaceGenerator.kt
src/test/resources/examples/multiMediaType/client/OpenFeignClient.kt
src/test/resources/examples/openFeignClient/api.yaml
src/test/resources/examples/openFeignClient/client/OpenFeignClient.kt
src/test/resources/examples/openFeignClient/client/SuspendableOpenFeignClient.kt

Closes #232 
Fix incorrect header parameters generation for OpenFeignClient where a new line was causing compilation errors

Fix incorrect header parameters generation for OpenFeignClient

---

src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt
src/main/kotlin/com/cjbooms/fabrikt/generators/controller/metadata/Micronaut.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/MicronautAuthenticationTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/MicronautControllerGeneratorTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/SpringAuthenticationTest.kt
src/test/kotlin/com/cjbooms/fabrikt/generators/SpringControllerGeneratorTest.kt

address a couple of compiler warnings and replace deprecated syntax

address a couple of compiler warnings and replace deprecated syntax

---

build.gradle.kts
src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt
src/test/kotlin/com/cjbooms/fabrikt/util/Linter.kt
src/test/resources/examples/authentication/controllers/spring/Controllers.kt
src/test/resources/examples/binary/controllers/micronaut/Controllers.kt
src/test/resources/examples/binary/controllers/spring/Controllers.kt
src/test/resources/examples/githubApi/controllers/micronaut/Controllers.kt
src/test/resources/examples/githubApi/controllers/spring/Controllers.kt
src/test/resources/examples/multiMediaType/api.yaml
src/test/resources/examples/okHttpClient/api.yaml
src/test/resources/examples/okHttpClient/models/Models.kt
src/test/resources/examples/parameterNameClash/controllers/micronaut/Controllers.kt
src/test/resources/examples/parameterNameClash/controllers/spring/Controllers.kt
src/test/resources/examples/pathLevelParameters/controllers/micronaut/Controllers.kt
src/test/resources/examples/springFormatDateAndDateTime/controllers/Controllers.kt

Uses the first 2xx content media found es primary response type #239
* Upgrade dependencies & linter
Closes #239

Uses the first 2xx content media found es primary response type #239

---

src/main/resources/templates/client-code/api-models.kt.hbs
src/main/resources/templates/client-code/http-util.kt.hbs
src/test/resources/examples/multiMediaType/client/ApiModels.kt
src/test/resources/examples/multiMediaType/client/HttpUtil.kt
src/test/resources/examples/okHttpClient/client/ApiModels.kt
src/test/resources/examples/okHttpClient/client/HttpUtil.kt
src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/ApiModels.kt
src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/HttpUtil.kt
src/test/resources/examples/parameterNameClash/client/ApiModels.kt
src/test/resources/examples/parameterNameClash/client/HttpUtil.kt
src/test/resources/examples/pathLevelParameters/client/ApiModels.kt
src/test/resources/examples/pathLevelParameters/client/HttpUtil.kt

Support 3xx http responses statuses in generated client code
Fixes #255

Support 3xx http responses statuses in generated client code

---

end2end-tests/models-jackson/build.gradle.kts
end2end-tests/models-jackson/openapi/api.yaml
end2end-tests/models-jackson/src/test/kotlin/com/cjbooms/fabrikt/models/jackson/DeepNestedPolymorphismTest.kt
end2end-tests/models-jackson/src/test/kotlin/com/cjbooms/fabrikt/models/jackson/EnumTest.kt
end2end-tests/models-jackson/src/test/kotlin/com/cjbooms/fabrikt/models/jackson/Helpers.kt
end2end-tests/models-jackson/src/test/kotlin/com/cjbooms/fabrikt/models/jackson/MapTest.kt
end2end-tests/models-jackson/src/test/kotlin/com/cjbooms/fabrikt/models/jackson/PolymorphismTest.kt
end2end-tests/models-jackson/src/test/resources/deep_nested_polymorphic/third_level_child11.json
end2end-tests/models-jackson/src/test/resources/deep_nested_polymorphic/third_level_child12.json
end2end-tests/models-jackson/src/test/resources/enums/array_of_enums.json
end2end-tests/models-jackson/src/test/resources/enums/enum_ref.json
end2end-tests/models-jackson/src/test/resources/enums/extensible_enum.json
end2end-tests/models-jackson/src/test/resources/enums/extensible_enum_ref.json
end2end-tests/models-jackson/src/test/resources/enums/inlined_enum.json
end2end-tests/models-jackson/src/test/resources/enums/list_of_enums.json
end2end-tests/models-jackson/src/test/resources/maps/complex_object_with_types_map.json
end2end-tests/models-jackson/src/test/resources/maps/inlined_object_map.json
end2end-tests/models-jackson/src/test/resources/maps/inlined_object_with_typed_map.json
end2end-tests/models-jackson/src/test/resources/maps/inlined_object_with_untyped_map.json
end2end-tests/models-jackson/src/test/resources/maps/inlined_string_map.json
end2end-tests/models-jackson/src/test/resources/maps/inlined_unknown_map.json
end2end-tests/models-jackson/src/test/resources/maps/object_map.json
end2end-tests/models-jackson/src/test/resources/maps/string_map.json
end2end-tests/models-jackson/src/test/resources/maps/typed_object_map.json
end2end-tests/models-jackson/src/test/resources/polymorphic/polymorphic_type_one.json
end2end-tests/models-jackson/src/test/resources/polymorphic/polymorphic_type_two.json
settings.gradle.kts

add end2end tests for jackson model generation

add end2end tests for jackson model generation

---

README.md

- updates version of the fabrikt-gradle-plugin in the readme
- adds a badge that always shows the latest version available in the Gradle Plugin Portal

Update version of fabrikt-gradle-plugin in README.md

---

src/main/kotlin/com/cjbooms/fabrikt/generators/controller/KtorControllerInterfaceGenerator.kt

Improve readability by adding in Ulrik's code improvement suggestion

Add Ulrik's code improvement suggestion

---

src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt
src/test/resources/examples/unsupportedInlinedDefinitions/controllers/spring/Controllers.kt

Minor improvement to handle String enums as Strings rather than Any.

Minor improvement to handle String enums as Strings.

---

end2end-tests/ktor/src/test/kotlin/com/cjbooms/fabrikt/servers/ktor/KtorQueryParametersTest.kt

Assert on the error when status is 400

Ktor server: Assert on error 400 message

---

README.md

Add publish instructions

---

README.md

I updated the gradle plugin to Fabrikt 24.1.2.

Update version of fabrikt-gradle-plugin in README.md to 1.20.1
