build.gradle.kts
Populates the project version from the git tag as described in https://github.com/palantir/gradle-git-version
=> Issue #6: Automate versioning management

.github/workflows/publish.yml
This action will publish the artifacts to maven central every time a release is created on github.
=> Action to promote the artifacts to maven central

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/model/ModelInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/main/kotlin/com/cjbooms/fabrikt/util/NormalisedString.kt, src/test/resources/examples/inLinedObject/api.yaml, src/test/resources/examples/inLinedObject/models/Models.kt, src/test/resources/examples/mapExamples/models/Models.kt
Closes #25 
When FabriKt encounters an inlined object definition it derives a class name using the property key. This was brittle and caused collisions for common property keys such as `type` or `name` that contained inline schemas.
To help alleviate the problem FabriKt now prefixes the derived class name with the Class Name of the enclosing top level schema definition. 
This will stop collisions between separate Schema entries which is the common case. Collisions will still occur if a single schema definition contains multiple inlined schema definitions, at different depths, that share key names.
=> ISSUE#25 When generating inlined object definitions prefix derived Class names 

src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGen.kt, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/MutableSettings.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/QuarkusReflectionModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/OkHttpClientGeneratorTest.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ResourceGeneratorTest.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/SpringControllerGeneratorTest.kt, src/test/kotlin/com/cjbooms/fabrikt/model/SourceApiTest.kt
`quarkus_reflection_config` target and `x_extensible_enums` model option aren't picked up by the client code gen
=> Issue #24 Fix client options

src/main/kotlin/com/cjbooms/fabrikt/generators/controller/ControllerGeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/SpringControllerInterfaceGenerator.kt, src/test/resources/examples/githubApi/controllers/Controllers.kt
Controller return types were accidentally changed in the migration to interfaces, and tests were adjusted to verify the bad behaviour.
=> Restoring ResponseEntity wrapper 

build.gradle.kts, src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpSimpleClientGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonMetadata.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinGenModels.kt, src/main/resources/templates/client-code/http-util.kt.hbs, src/test/kotlin/com/cjbooms/fabrikt/generators/OkHttpClientGeneratorTest.kt, src/test/resources/examples/okHttpClient/client/ApiClient.kt, src/test/resources/examples/okHttpClient/client/HttpUtil.kt
Return types such as `Map<String, Any>?` are now supported using TypeReference
=> ISSUE#44 Fixing client generation code for generic typed responses 

src/main/resources/templates/client-code/http-util.kt.hbs, src/test/resources/examples/okHttpClient/client/HttpUtil.kt
The parameters are concatenated by default with ", ", leaving a space between the comma and the next parameter
=> Fixing bug when generating HTTP parameters on an non-exploded format.

src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/resources/examples/defaultValues/models/Models.kt, src/test/resources/examples/enumExamples/models/Models.kt, src/test/resources/examples/externalReferences/models/Models.kt, src/test/resources/examples/githubApi/models/Models.kt, src/test/resources/examples/githubApi/resources/reflection-config.json, src/test/resources/examples/javaSerializableModels/models/Models.kt, src/test/resources/examples/okHttpClient/models/Models.kt, src/test/resources/examples/quarkusReflectionModels/models/Models.kt
Inlined enums now get a class name prefixed with the class name that declares them. This should help avoid conflicts between enums with the same name inlined in different schemas
=> Improvements to inlined enum class generation.

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/resources/examples/externalReferences/external-models.yaml, src/test/resources/examples/externalReferences/models/Models.kt
When this occurs, simply parse the entire external API spec, and generate models for every schema within it. We could be more targeted with this but attempts I made to do so were resulting in quite complicated code.
=> ISSUE-60 Adding logic to detect when an schema is referenced in an external API document

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/TypeFactory.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/model/OasType.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/resources/examples/externalReferences/external-models.yaml, src/test/resources/examples/externalReferences/models/Models.kt, src/test/resources/examples/mapExamples/api.yaml, src/test/resources/examples/mapExamples/models/Models.kt
It is now possible to specify maps of maps in additional properties section via:
```
additionalProperties:
type: object
additionalProperties:
$ref: '#/components/schemas/ExternalObjectFour'
```
=> Support for additional properties being maps of maps

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonMetadata.kt, src/test/resources/examples/externalReferences/models/Models.kt, src/test/resources/examples/githubApi/models/Models.kt, src/test/resources/examples/mapExamples/models/Models.kt
Adding in Jackson annotations and getter to allow for additional properties to be serialised back to json as top level properties. Previously deserialisation worked, but on re-serialisation they were being placed inside a map called properties.
=> Serialize additional properties as top level json properties

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/main/kotlin/com/cjbooms/fabrikt/util/NormalisedString.kt, src/test/kotlin/com/cjbooms/fabrikt/util/NormalisedStringTest.kt, src/test/resources/examples/enumExamples/api.yaml, src/test/resources/examples/enumExamples/models/Models.kt, src/test/resources/examples/okHttpClient/client/ApiClient.kt, src/test/resources/examples/okHttpClient/client/ApiService.kt, src/test/resources/examples/okHttpClientMultiMediaType/client/ApiClient.kt, src/test/resources/examples/okHttpClientMultiMediaType/client/ApiService.kt
Improved generation to support ENUM values containing special characters and classes containing numbers
This schmea:
```yaml
ContentType:
type: string
x-extensible-enum:
- application/json
- application/x.some-type+json    
- application/x.some-other-type+json;version=2  
```
Will now produce this enum class:
```kotlin
enum class ContentType(
@JsonValue
val value: String
) {
APPLICATION_JSON("application/json"),
APPLICATION_X_SOME_TYPE_JSON("application/x.some-type+json"),
APPLICATION_X_SOME_OTHER_TYPE_JSON_VERSION_2("application/x.some-other-type+json;version=2");
}
```
=> Improving the Normalised String utilities.

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/test/resources/examples/defaultValues/models/Models.kt, src/test/resources/examples/enumExamples/api.yaml, src/test/resources/examples/enumExamples/models/Models.kt, src/test/resources/examples/enumPolymorphicDiscriminator/models/Models.kt, src/test/resources/examples/externalReferences/models/Models.kt, src/test/resources/examples/githubApi/models/Models.kt, src/test/resources/examples/javaSerializableModels/models/Models.kt, src/test/resources/examples/micronautIntrospectedModels/models/Models.kt, src/test/resources/examples/okHttpClient/models/Models.kt, src/test/resources/examples/okHttpClientMultiMediaType/models/Models.kt, src/test/resources/examples/quarkusReflectionModels/models/Models.kt
Adds the following `fromValue` reverse lookup function to generated enums:
```kotlin
enum class ContentType(
@JsonValue
val value: String
) {
APPLICATION_JSON("application/json"),
APPLICATION_X_SOME_TYPE_JSON("application/x.some-type+json"),
APPLICATION_X_SOME_OTHER_TYPE_JSON_VERSION_2("application/x.some-other-type+json;version=2");
companion object {
private val mapping: Map<String, ContentType> = values().associateBy(ContentType::value)
fun fromValue(value: String): ContentType? = mapping[value]
}
}
```
=> Adding reverse lookup function to generated enums

README.md, src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt, src/test/resources/examples/okHttpClientMultiMediaType/api.yaml, src/test/resources/examples/okHttpClientMultiMediaType/client/ApiClient.kt, src/test/resources/examples/okHttpClientMultiMediaType/client/ApiService.kt, src/test/resources/examples/okHttpClientMultiMediaType/models/Models.kt
Currently if there are multiple response schemas, the client just generates the response class for the first one. This changes it so that it generates JsonNode when there are multiple possible response schemas.
=> Multiple response content types

src/test/kotlin/com/cjbooms/fabrikt/util/YamlUtilsTest.kt
Adds a test to validate #92 is fixed
=> Adding test and validating that it fails with the older version of Kaizen parser

src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt, src/test/resources/examples/oneOfPolymorphicModels/api.yaml, src/test/resources/examples/oneOfPolymorphicModels/models/Models.kt
The reference to the enum value `ParentType.CHILD_TYPE_A`  in `ChildTypeA` in the example, was previously referencing `ParentType.CHILDTYPEA`
=> Fix enum reference

README.md
The task should inform to Gradle what are the input and output files so it can manage the build cache.
Closes #88
=> Updating Gradle example in README

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonMetadata.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/test/resources/examples/oneOfPolymorphicModels/models/Models.kt
When the discriminator is an x-extensible-enum, the enum value should be used to select the subtype, not the class name as a string.
=> Use x-extensible-enum value for json subtype annotation

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/test/resources/examples/enumPolymorphicDiscriminator/api.yaml, src/test/resources/examples/enumPolymorphicDiscriminator/models/Models.kt
There are cases as in the added example where it's desirable to have a polymorphic subtype that is just a marker class containing a hard-coded discriminator value
=> Only make it a data class if there are constructor parameters. 

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/test/resources/examples/enumPolymorphicDiscriminator/api.yaml, src/test/resources/examples/enumPolymorphicDiscriminator/models/Models.kt, src/test/resources/examples/githubApi/resources/reflection-config.json
A bug was introduced that was causing top-level schema definitions to be generated as part of the inlined generation logic. This resulted in complex polymorphic classes getting over-written with simpler inline-derived versions.
This PR removes the logic that generates referenced schemas during inline generation. It relies on the fact that these schemas will undergo regular/full generation.
Closes #103
=> Fix inline generation bug #103

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/OkHttpClientGeneratorTest.kt, src/test/resources/examples/githubApi/resources/reflection-config.json, src/test/resources/examples/okHttpClient/models/Models.kt, src/test/resources/examples/okHttpClientMultiMediaType/models/Models.kt
Arrays were still triggering inline generation logic for full schemas. This disables that logic
closes #103
=> Disable inline generation of full schema objects from array generation

README.md, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/model/OasType.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/resources/examples/githubApi/models/Models.kt
Similar to the UUID handling that has already been added (#57). This matches the behavior of openapi-generator.
=> Map strings with format: uri to java.net.URI

src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpEnhancedClientGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpSimpleClientGenerator.kt, src/test/resources/examples/okHttpClient/api.yaml, src/test/resources/examples/okHttpClient/client/ApiClient.kt, src/test/resources/examples/okHttpClient/client/ApiService.kt
ISSUE-119: Support naming http client methods after the operationId
Closes #119
=> Support naming http client methods after the operationId

src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpSimpleClientGenerator.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/OkHttpClientGeneratorTest.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/api.yaml, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/ApiClient.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/ApiModels.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/ApiService.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/HttpResilience4jUtil.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/HttpUtil.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/LoggingInterceptor.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/OAuth.kt
The `.` got lost. Also okhttp3 always once *some* payload, so in cases where no data should be sent, an empty buffer must be passed in.
=> fix broken codegen for put/post/patch requests without request body

src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt, src/main/resources/templates/client-code/http-util.kt.hbs, src/test/resources/examples/okHttpClient/client/ApiClient.kt, src/test/resources/examples/okHttpClient/client/ApiService.kt, src/test/resources/examples/okHttpClient/client/HttpUtil.kt, src/test/resources/examples/okHttpClientMultiMediaType/client/ApiClient.kt, src/test/resources/examples/okHttpClientMultiMediaType/client/ApiService.kt, src/test/resources/examples/okHttpClientMultiMediaType/client/HttpUtil.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/ApiClient.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/ApiService.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/HttpUtil.kt, src/test/resources/examples/parameterNameClash/client/ApiClient.kt, src/test/resources/examples/parameterNameClash/client/ApiService.kt, src/test/resources/examples/parameterNameClash/client/HttpUtil.kt, src/test/resources/examples/pathLevelParameters/client/ApiClient.kt, src/test/resources/examples/pathLevelParameters/client/ApiService.kt, src/test/resources/examples/pathLevelParameters/client/HttpUtil.kt
ISSUE-120: The http client will now return a non-nullable response type ~~on those operations that define a unique 200 successful response~~ such as follows:
```
no content -> ApiResponse<Unit>
single content schema: MyTypeOne -> ApiResponse<MyTypeOne>
multiple content schemas: -> ApiResponse<JsonNode> or ApiResponse<Any> 
```
Closes #120
=> Non-Nullable client return types

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt, src/test/resources/examples/enumExamples/api.yaml, src/test/resources/examples/enumExamples/models/Models.kt
All enums inside arrays were being treated as inlined definitions, even when they are not.
=> Fix inline enum detection in arrays.

src/main/kotlin/com/cjbooms/fabrikt/generators/OasDefault.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt, src/test/resources/examples/defaultValues/api.yaml, src/test/resources/examples/defaultValues/models/Models.kt, src/test/resources/examples/okHttpClient/api.yaml, src/test/resources/examples/okHttpClient/client/ApiClient.kt, src/test/resources/examples/okHttpClient/client/ApiService.kt
- URI format string types did correctly handle default values. It produced compile-time errors because of: `uriType: URI = "http://some-uri"`.
- Default handling of parameters in generated clients was also incorrect, this has code path now uses the same default handling logic which has been moved to a dedicated class.
=> Fix handling of default values.

src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt, src/test/resources/examples/okHttpClient/client/ApiClient.kt, src/test/resources/examples/okHttpClient/client/ApiService.kt, src/test/resources/examples/okHttpClientMultiMediaType/client/ApiClient.kt, src/test/resources/examples/okHttpClientMultiMediaType/client/ApiService.kt
If the spec says a parameter is not required, then the client APIs should provide default null values to save the builder from doing so.
=> Add null parameter defaults when not required.

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/test/resources/examples/anyOfOneOfAllOf/models/Models.kt, src/test/resources/examples/externalReferences/models/Models.kt, src/test/resources/examples/githubApi/models/Models.kt, src/test/resources/examples/mapExamples/models/Models.kt
This will ensure that additional properties are taken into account with equality check. Previously data classes containing different additional properties were being reported as equal if all constructor parameters matched
=> Move additional properties map to data class constructor.

README.md, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGen.kt, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenArgs.kt, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt, src/main/kotlin/com/cjbooms/fabrikt/cli/MarkdownUsageFormatter.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/MutableSettings.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/instantDateTime/api.yaml, src/test/resources/examples/instantDateTime/models/Models.kt
Adds a configuration parameter to allow builders to override the types generated by fabrikt. 
| | |
| --- | --- |
|   `--type-overrides`         | Specify non-default kotlin types for certain OAS types. For example, generate `Instant` instead of `OffsetDateTime` |
|                              | CHOOSE ANY OF: |
|                              |   `DATETIME_AS_INSTANT` - Use `Instant` as the datetime type. Defaults to `OffsetDateTime` |
|                              |   `DATETIME_AS_LOCALDATETIME` - Use `LocalDateTime` as the datetime type. Defaults to `OffsetDateTime` |
=> Allow builders to configure the kotlin types generated 

README.md, build.gradle.kts, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGen.kt, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenArgs.kt, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/JavaxValidationAnnotations.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/MutableSettings.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/jakartaValidationAnnotations/api.yaml, src/test/resources/examples/jakartaValidationAnnotations/models/Models.kt, src/test/resources/examples/validationAnnotations/jakarta/models/Models.kt
Added CLI option `--validation-library` with default value JAVAX_VALIDATION and optional value JAKARTA_VALIDATION to allow generated model classes to support either
=> Support jakarta.validation for model classes

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt
I am interested in taking on issue #89, to support `kotlinx.serialization`.
In preparation, I checked out `master` and observed that dependencies were generally somewhat out-of-date.  I've updated them here before adding support for the latest `kotlinx.serialization` version.
A couple of minor changes arose to account for the new dependencies:
1. Dokka now prefers to expose a task-per-output-format, than have a single output format selected.  I imagine this is to support output of multiple formats.  The way the task is acquired for the `kotlinDocJar` task then had to change.
2. Kotlin Poet now supports multple 'simpleName's; I'm not sure why to be honest but fixing our usage was a simple case of removing the single argument label.
Unit tests passing locally ✅
=> General dependency update

README.md, build.gradle.kts, src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/jsonMergePatch/api.yaml, src/test/resources/examples/jsonMergePatch/models/Models.kt
Fixes #184 
I added support for an extension called `x-json-merge-patch`. Schemas annotated with that extension wrap all their fields in a `JsonNullable`. The effect applies to all nested objects as well but not to `$ref`ed types. This is the usual behavior as described in RFC 7386 but also allows for custom behavior, should the need exist.
I'm not sure why or how one would combine this feature with discriminator-based polymorphism, so I didn't write any tests for it, but in theory, I added support for that as well.
=> Support json merge patch

src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/discriminatedOneOf/api.yaml, src/test/resources/examples/discriminatedOneOf/models/Models.kt
This is something very few code generators even try to implement, but it was fairly easy to add to fabrikt. Currently we use inheritance because that's what openapi-generator supports, but apparently the OpenAPI spec people have the opinion that oneOf should be used for modelling sum types[^1]. This is also the only way to model these that is properly supported by swagger-ui.
The implementation is a bit of a rough sketch, but works for my use-case, which I added as a test case in reduced form. I'm very open for feedback, especially around the differentiation of "normal" oneOf's that are generated as Any type and discriminated ones (oneOfSuperInterface called in the implementation).
Some notes:
* it uses sealed *interfaces* in order to not conflict with any existing inheritance, which are …
=> Add support for disciminated oneOf's

src/main/kotlin/com/cjbooms/fabrikt/generators/OasDefault.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt, src/test/resources/examples/jsonMergePatch/api.yaml, src/test/resources/examples/jsonMergePatch/models/Models.kt
Introduced in #189 , the "JSON Merge Patch" pattern implemented via `JsonNullable` still has some rough edges like bugs with nullability of the inner type parameters as well as with default values of properties. Both should be fixed with this PR.
=> Fix nullability and default value issues for JSON merge patch

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/test/resources/examples/companionObject/models/Models.kt, src/test/resources/examples/enumPolymorphicDiscriminator/models/Models.kt, src/test/resources/examples/externalReferences/models/Models.kt, src/test/resources/examples/javaSerializableModels/models/Models.kt, src/test/resources/examples/micronautIntrospectedModels/models/Models.kt, src/test/resources/examples/micronautReflectionModels/models/Models.kt, src/test/resources/examples/nestedPolymorphicModels/models/Models.kt, src/test/resources/examples/okHttpClient/models/Models.kt, src/test/resources/examples/okHttpClientMultiMediaType/models/Models.kt, src/test/resources/examples/oneOfPolymorphicModels/models/Models.kt, src/test/resources/examples/polymorphicModels/models/Models.kt, src/test/resources/examples/polymorphicModels/sealed/models/Models.kt, src/test/resources/examples/quarkusReflectionModels/models/Models.kt
Since moving the discriminator property from the class into the constructor, we need to have the parameter annotation also. Closes #219
=> Add missing JsonProperty parameter annotation.

src/main/kotlin/com/cjbooms/fabrikt/model/SourceApi.kt
Was browsing through the codebase and found these two redundant conditions. Unless I'm missing something, these conditions are already subsumed in the `if` block above, correct? We could remove them.
=> Remove redundant checks for co-occurrence of properties and combiners

src/main/kotlin/com/cjbooms/fabrikt/generators/OasDefault.kt, src/main/kotlin/com/cjbooms/fabrikt/util/NormalisedString.kt, src/test/kotlin/com/cjbooms/fabrikt/util/NormalisedStringTest.kt, src/test/resources/examples/defaultValues/api.yaml, src/test/resources/examples/defaultValues/models/Models.kt, src/test/resources/examples/enumExamples/api.yaml, src/test/resources/examples/enumExamples/models/Models.kt
Add backticks to the enum item name in case it doesn't start with a letter or an underscore and hence is not a valid Kotlin identifier.
Fixes #241.
=> Quote enum item names when necessary

src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/singleAllOfProperty/api.yaml, src/test/resources/examples/singleAllOfProperty/models/Models.kt
Previously, a property with an `allOf` type with a single `$ref` would generate a model property with a type derived from the name of the property instead of the type referenced by $ref. This fixes #246.
This commit implements the first solution mentioned in #246, i.e.
```yaml
Dog:
type: object
properties:
owner:
description: "The registered owner of the dog."
allOf:
- $ref: "#/components/schemas/Person"
walker:
description: "The person walking the dog."
allOf:
- $ref: "#/components/schemas/Person"
Person:
type: object
required:
- name
properties:
name:
type: string
```
will generate data classes where the properties `owner` and `walker` have type `Person` instead of `Owner` and `Walker`.
```kotlin
public data class Dog(
@param:JsonProperty("owner")
@get:JsonProperty("owner")
@get:Valid …
```
=> Support schemas having properties with an "allOf with single $ref" type (#246)

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt
This pull request adds support for OpenAPI 3.0 style nullable references:
```yaml
foo:
nullable: true
allOf:
- $ref: '#/components/schemas/Foo'
```
by special casing `allOf` with one entry and respecting either the allOfSchema or the "parent" schema being nullable.
=> Support allOf with a single object in combination with nullable

src/main/kotlin/com/cjbooms/fabrikt/util/YamlUtils.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/openapi310/api.yaml, src/test/resources/examples/openapi310/models/Models.kt
Fabrikt will now detect of the newer 3.1.0 specification is declared and automatically downgrade any of the json schema nullable types to the previous format. EG, this:
```
NewNullableFormat:
type: object
required:
- version
properties:
version:
type:
- string
- 'null'
```
Will get converted to this:
```
NewNullableFormat:
type: object
required:
- version
properties:
version:
type: string
nullable: true
```
Related to #262
=> Supported OpenApi 3.1.0 nullable changes.

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/test/resources/examples/jsonMergePatch/models/Models.kt, src/test/resources/examples/openapi310/models/Models.kt, src/test/resources/examples/optionalVsRequired/api.yaml, src/test/resources/examples/optionalVsRequired/models/Models.kt
If a required property has its schema flagged as nullable, it is no longer flagged as a non null.
=> Add support for nullable keyword.

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt, src/test/resources/examples/enumPolymorphicDiscriminator/api.yaml, src/test/resources/examples/enumPolymorphicDiscriminator/models/Models.kt
When an inline schema is inherited, the child should reference the parent definition, and not build ain incompatible child version
=> Fix inline schema definitions inherited from a parent.

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/discriminatedOneOf/models/Models.kt
As per title and Issue #258 it does not seem correct to be stripping a declared property from the data classes.
Instead, adopt the same approach as allOf polymorphism and default the discriminator to the correct value
=> Do not strip discriminator property in oneOf generation.

src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/resources/examples/discriminatedOneOf/api.yaml, src/test/resources/examples/discriminatedOneOf/models/Models.kt
After #268 was merged it seems like additional properties in the generated model has an incorrect default value.
The test for discriminatedOneOf illustrates the issue: StateBMode has it's default value set to a non existent enum value - which looks like the value of the discriminator field.
~~I would love to assist with a fix, but I am simply not familiar enough with the codebase to be able to identify where to start.~~
I have taken my best shot at fixing the issue. Let me know what you think.
I notice that the ordering of properties in the model is different from the order in the spec, but perhaps that's intentional?
=> Issue with default value for additional property (oneOf)

src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/oneOfMarkerInterface/api.yaml, src/test/resources/examples/oneOfMarkerInterface/models/Models.kt
While the discriminator property is needed to enable full polymorphism with Jackson, it should not be a blocker to  applying the sealed interface to classes that deserve it.
This PR allows the interface to be applied, without the Jackson polymorphism annotations:
```
public sealed interface State
public data class StateA(
@get:JsonProperty("status")
@get:NotNull
public val status: String,
) : State
public data class StateB(
@get:JsonProperty("mode")
@get:NotNull
public val mode: String,
) : State
```
Jackson won't be able to figure out which object to deserialise to, but it is beneficial to have the marker interface in code
=> Support adding marker interface to oneOfs.

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/TypeFactory.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpEnhancedClientGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/OkHttpSimpleClientGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/OpenFeignInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/test/resources/examples/anyOfOneOfAllOf/models/Models.kt, src/test/resources/examples/externalReferences/aggressive/models/Models.kt, src/test/resources/examples/externalReferences/targeted/models/Models.kt, src/test/resources/examples/githubApi/models/Models.kt, src/test/resources/examples/jakartaValidationAnnotations/models/Models.kt, src/test/resources/examples/mapExamples/models/Models.kt, src/test/resources/examples/wildCardTypes/models/Models.kt
From what I can see, there does not appear to be a way to specify that Map values should be null or non-null in an OpenApi3 specification. We therefore need to make all map values nullable. 
I have a case where I need to preserve nulls in an untyped object, and cannot achieve that without this change
=> Map values should be nullable.

README.md, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/TypeFactory.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/mapExamplesNonNullValues/api.yaml, src/test/resources/examples/mapExamplesNonNullValues/models/Models.kt
Adopting the latest version of fabrikt, where the default nullability of map values has changed proved to be a PITA. Adding a configuration option to allow users to opt back in to previous behaviour via:
`--http-model-opts` `NON_NULL_MAP_VALUES`
=> Allow configuration of Map value nullability.

README.md, build.gradle.kts, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/AnnotationBasedControllerInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/ControllerInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/KtorControllerInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/MicronautControllerInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/SpringControllerInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinGenModels.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/KtorControllerInterfaceGeneratorTest.kt, src/test/resources/examples/authentication/controllers/ktor/Controllers.kt, src/test/resources/examples/binary/controllers/ktor/Controllers.kt, src/test/resources/examples/githubApi/controllers/ktor/Controllers.kt, src/test/resources/examples/parameterNameClash/controllers/ktor/Controllers.kt, src/test/resources/examples/pathLevelParameters/controllers/ktor/Controllers.kt, src/test/resources/examples/singleAllOf/controllers/ktor/Controllers.kt
Inspired by #214, Ktor server code is generated as a controller interface with methods for the routes along with a companion object which is used for mounting the routes on the Ktor server (see example further down).
Ktor is by design very flexible, and thus in order for us to be able to generate code we need to make certain design decisions. The approach with routing function + an interface should work well for most cases. The users are still free to configure Ktor however they like, including where they mount the routes and how the implement the controller interface.
Ktor's ApplicationCall is passed to the controller methods to allow them to perform additional logic on the incoming/outgoing request. One might desire to create an extension function for resolving the current user or …
=> Ktor server routes and controller interfaces

src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/ControllerInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/KtorControllerInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/MicronautControllerInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/SpringControllerInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinGenModels.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/KtorControllerInterfaceGeneratorTest.kt, src/test/resources/examples/authentication/controllers/ktor/Controllers.kt, src/test/resources/examples/binary/controllers/ktor/Controllers.kt, src/test/resources/examples/githubApi/controllers/ktor/Controllers.kt, src/test/resources/examples/parameterNameClash/controllers/ktor/Controllers.kt, src/test/resources/examples/pathLevelParameters/controllers/ktor/Controllers.kt, src/test/resources/examples/singleAllOf/controllers/ktor/Controllers.kt
In #280 it was discussed how to provide the user with a type safe way to respond to the request.
It was [decided](https://github.com/cjbooms/fabrikt/pull/280#discussion_r1579041527) to fully delegate the responsibility of responding to the controller implementation, which provides the user with direct access to `call` and maintains full flexibility.
In order to be able to offer a type safe way to respond, this PR introduces two new functions on `call`:
- `call.repondTyped(status: HttpStatusCode, message: T)`
- `call.repondTyped(message: T)`
The functions are provided through a decorator on ApplicationCall (which is luckily an interface) and can be used as a drop-in replacement for ApplicationCall.
The `TypedApplicationCall` class is included as a utility class through a `generateLibrary` …
=> Ktor typed respond functions

src/main/kotlin/com/cjbooms/fabrikt/generators/controller/KtorControllerInterfaceGenerator.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/KtorControllerInterfaceGeneratorTest.kt, src/test/resources/examples/requestBodyAsArray/api.yaml, src/test/resources/examples/requestBodyAsArray/controllers/ktor/Controllers.kt
Fixes an issue where invalid code was generated when request body is an list of models.
The issue was caused by a too simple method for outputting the type of the parameter.
Without this fix, the code would look like this which clearly does not compile:
```kotlin
val requestBody = call.receive<Book>>()
```
=> Use KotlinPoet %T for call.receive

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/JacksonModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/requiredButNullableObjectProperty/api.yaml, src/test/resources/examples/requiredButNullableObjectProperty/models/RequiredButNullableObjectProperty.kt
* test: Created test for an object that has a required but nullable field
* test: Created test for an array of nullable items
* test: Updated `details` model with a nullable map of nullable values
* refactor: Replaced if/else-if with when in `createModels`
* test: Updated `NullableArrayItems` to be nullable
* refactor: Style changes to be more consistent
* fix: Nullable object fields (among others) now work as expected
* test: Removed nullableArrayItems test for now
=> fix: Nullable object fields now working as expected (#291)

src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/resources/examples/arrays/api.yaml, src/test/resources/examples/arrays/models/ContainsArrayOfArrays.kt, src/test/resources/examples/arrays/models/ContainsArrayOfArraysAbsentObjectTypeInArray.kt
Need to be lenient with inline object definitions like we are with top-level, and not require explicit `type: object` non-empty properties should be enough to assume object intent
=> Fix Jens issue around nested arrays missing explicit object type.

README.md, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/OpenFeignInterfaceGenerator.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/OpenFeignClientGeneratorTest.kt, src/test/resources/examples/openFeignClient/client/OpenFeignClientWithResponseEntity.kt
This adds a configuration option for "http-client-opts" to configurably add the Spring ResponseEntity<> generic around the response type of feign client functions.
This enables the option to get the status code and headers from the response of the external server.
This currently imports  the typeName for ResponseEntity from "com.cjbooms.fabrikt.generators.controller.metadata.SpringImports.RESPONSE_ENTITY" as it was previously only needed in the controllers and i didn't want to duplicate it.
Maybe a different location would be better?
=> Add an option to add spring ResponseEntity for feign client return type

src/main/kotlin/com/cjbooms/fabrikt/generators/OasDefault.kt, src/test/resources/examples/defaultValues/api.yaml, src/test/resources/examples/defaultValues/models/PersonWithDefaults.kt
=> Fix BigDecimal defaults.

README.md
This PR restructures and refreshes the README in order to bring it up to date with what Fabrikt offers as of September 2024.
The contents are more or less the same, but I have tried to cater more to the users and to put an emphasis on how to get started.
=> Restructures and refreshes the README

end2end-tests/ktor/src/test/kotlin/com/cjbooms/fabrikt/servers/ktor/KtorAuthenticationTest.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/KtorControllerInterfaceGenerator.kt, src/test/resources/examples/authentication/api.yaml, src/test/resources/examples/authentication/controllers/ktor/Controllers.kt
`authenticate()` accepts a vararg and by default allows the API access if at least one option is satisfied.
=> Allow having multiple authentication alternatives in Ktor controllers

src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/ControllerGeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/ModelGenerator.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/KotlinSerializationModelGeneratorTest.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/OkHttpClientGeneratorTest.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/OpenFeignClientGeneratorTest.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ResourceGeneratorTest.kt
With the addition of `kotlinx.serialization` (#327) JacksonModelGenerator is now simply `ModelGenerator`.
=> JacksonModelGenerator is now simply ModelGenerator

README.md
This PR aims to enhance the Fabrikt README by adding helpful pointers to ensure users can get the most out of the tool 🚀.
There are a few well-known gotchas that have been raised in issues, so we thought it would be valuable to document them here. This should reduce the chances of users giving up on Fabrikt with the impression that “It’s not working!” and instead help them troubleshoot effectively.
Any other gotchas worth mentioning? 
Cc/ @cjbooms, @acanda, @averabaq, ..?
=> Add usage tips to README

build.gradle.kts, end2end-tests/ktor/build.gradle.kts, end2end-tests/models-jackson/build.gradle.kts, end2end-tests/models-kotlinx/build.gradle.kts, end2end-tests/okhttp/build.gradle.kts, end2end-tests/openfeign/build.gradle.kts
Upgrades Kotlin to 2.0.20. Shouldn't change anything, but we might as well keep up with the latest major version of Kotlin.
`Kotlinx.Serialization` is also upgraded as `1.7.3` [uses 2.0.20 by default](https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.7.3). This affects only the end2end test.
=> Upgrade to Kotlin 2.0.20

build.gradle.kts, end2end-tests/ktor/src/test/kotlin/com/cjbooms/fabrikt/servers/ktor/KtorAuthenticationTest.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/KtorControllerInterfaceGenerator.kt, src/test/resources/examples/authentication/controllers/ktor/Controllers.kt
This PR adapts the Ktor Controller Interface Generator to support Ktor Server 3.0.1.
Upgrading to Ktor Server 3.0.1 means letting go of the 'principal' parameter to the controller functions. The [Principal interface](https://api.ktor.io/ktor-server/ktor-server-plugins/ktor-server-auth/io.ktor.server.auth/-principal/index.html) is no longer available and thus we cannot provide a common supertype of the different Principals. Instead the user should get the principal with `call.principal<P>()` in the implementation. This will work just fine with Ktor 2.3.x too.
=> Upgrade to Ktor Server 3.0.1

src/main/kotlin/com/cjbooms/fabrikt/util/YamlUtils.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/openapi310OptionalObject/api.yaml, src/test/resources/examples/openapi310OptionalObject/models/NullableObject.kt, src/test/resources/examples/openapi310OptionalObject/models/TheObject.kt
Currently mapping from openapi 3.1.0 nullable types only works with the types array which does not support object. This pr provides mapping for `oneOf (object | null)` to the legacy style mapping. See the following input openapi spec:
```yaml
openapi: 3.1.0
components:
schemas:
NullableObject:
type: object
properties:
field:
oneOf:
- type: 'null'
- $ref: '#/components/schemas/TheObject'
TheObject:
properties:
name:
type: string
```
It would be updated to this openapi spec after this pr:
```yaml
openapi: 3.1.0
components:
schemas:
NullableObject:
type: object
properties:
field:
allOf:
- $ref: '#/components/schemas/TheObject'
nullable: true
TheObject:
properties:
name:
type: string
```
=> Implement support for optional objects in openapi 3.1.0

end2end-tests/models-kotlinx/openapi/api.yaml, src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/ModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/JacksonAnnotations.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinxSerializationAnnotations.kt, src/main/kotlin/com/cjbooms/fabrikt/model/SerializationAnnotations.kt, src/test/resources/examples/discriminatedOneOf/models/kotlinx/StateA.kt, src/test/resources/examples/discriminatedOneOf/models/kotlinx/StateB.kt
Discriminated oneOf models generated with Kotlin serialization will currently not work because the discriminator property causes a name conflict with Kotlin Serialization's class discriminator:
`Sealed class 'subclass' cannot be serialized as base class 'com.example.models.Superclass' because it has property name that conflicts with JSON class discriminator 'type'.`
The issue was not discovered earlier because the OpenAPI spec for end-2-end test for Kotlin serialization models did not define the discriminator property on the child schemas. This PR adds the missing `type` property to the test.
In order for the generated code to be valid with Kotlin serialization we must omit the property in the models. The solution in this PR is to simply skip adding the property as part of the code …
=> Omit discriminator property for Kotlin serialization

end2end-tests/models-kotlinx/openapi/api.yaml, end2end-tests/models-kotlinx/src/test/kotlin/com/cjbooms/fabrikt/models/kotlinx/KotlinxSerializationOneOfPolymorphicTest.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinxSerializationAnnotations.kt, src/test/resources/examples/discriminatedOneOf/models/kotlinx/State.kt
This PR adds support for polymorphic discriminators with names other than "type", which is the default class discriminator used by Kotlin serialization.
Non-default class disciminators are defined using the `JsonClassDiscriminator` annotation ([docs](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-json/kotlinx.serialization.json/-json-class-discriminator/)) and requires opt-in by the user.
=> Kotlin serialization custom discriminator name

.github/workflows/deploy-playground-prod.yml, README.md, playground/Dockerfile, playground/README.md, playground/build.gradle.kts, playground/fly.toml, playground/src/main/kotlin/PlaygroundApplication.kt, playground/src/main/kotlin/data/SampleData.kt, playground/src/main/kotlin/lib/GenerateCodeSynchronized.kt, playground/src/main/kotlin/lib/GenerationSettings.kt, playground/src/main/kotlin/views/HtmlUtils.kt, playground/src/main/kotlin/views/elements/CodeView.kt, playground/src/main/kotlin/views/elements/EnumCheckboxes.kt, playground/src/main/kotlin/views/elements/EnumSelectBox.kt, playground/src/main/kotlin/views/elements/FileList.kt, playground/src/main/kotlin/views/elements/FileView.kt, playground/src/main/kotlin/views/elements/InputBox.kt, playground/src/main/kotlin/views/elements/SpecForm.kt, playground/src/main/kotlin/views/layout/ColumnPanel.kt, playground/src/main/kotlin/views/layout/Layout.kt, playground/src/main/resources/logback.xml, playground/src/main/resources/static/main.css, playground/src/test/kotlin/lib/GenerationSettingsTest.kt, settings.gradle.kts, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/MutableSettings.kt
What if we gave everyone the opportunity to try Fabrikt with minimal investment? Could it motivate people to invest the time and effort needed to integrate Fabrikt into their projects and thereby drive adoption? What would it take to build such a thing?
This idea sparked the creation of an initial version of an interactive playground.
While it brings absolutely zero improvements to the code generation aspects of Fabrikt, I had fun making it, and perhaps it will be useful for people.
It is currently structured as a Gradle module and part of the main repository. It could also be split out into a separate repository (which would align with how the Gradle plugin is maintained).
It uses a blend of [Ktor](https://ktor.io/), [Kotlin HTML DSL](https://kotlinlang.org/docs/typesafe-html-dsl.html), …
=> Interactive Playground

src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/model/ModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/model/OasType.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/resources/examples/mapExamples/api.yaml, src/test/resources/examples/mapExamples/models/BasicObjectWithBooleanMap.kt, src/test/resources/examples/mapExamples/models/BasicObjectWithNumberMap.kt, src/test/resources/examples/mapExamples/models/BasicObjectWithStringMap.kt
I encountered this issue in Zalando today. The additional properties declaring simple types was not working.
The code generation in this area is crazy brittle and hard to follow, but I think I have a solution here that gets this working in the most minimally impactful way.
=> Add support for additional properties with simple types.

src/main/kotlin/com/cjbooms/fabrikt/generators/model/ModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/model/SourceApi.kt, src/main/kotlin/com/cjbooms/fabrikt/util/ModelNameRegistry.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/SpringControllerGeneratorTest.kt, src/test/resources/examples/arrays/api.yaml, src/test/resources/examples/arrays/controllers/spring/Controllers.kt, src/test/resources/examples/arrays/models/ArrayContainingComplexInlined.kt, src/test/resources/examples/enumExamples/models/Bar.kt, src/test/resources/examples/enumExamples/models/Foo.kt, src/test/resources/examples/modelSuffix/models/BarDto.kt, src/test/resources/examples/modelSuffix/models/FooDto.kt
Fix issue with generation of inlined items schema in arrays, as seem in this screenshot, where the nested array items is getting duplicate model named, but is not referenced as such:
Related to #352
=> Fix issue with generation of inlined items schema in arrays.

src/main/resources/templates/client-code/http-util.kt.hbs, src/test/resources/examples/byteArrayStream/client/HttpUtil.kt, src/test/resources/examples/externalReferences/aggressive/client/HttpUtil.kt, src/test/resources/examples/multiMediaType/client/HttpUtil.kt, src/test/resources/examples/okHttpClient/api.yaml, src/test/resources/examples/okHttpClient/client/ApiClient.kt, src/test/resources/examples/okHttpClient/client/ApiService.kt, src/test/resources/examples/okHttpClient/client/HttpUtil.kt, src/test/resources/examples/okHttpClientPostWithoutRequestBody/client/HttpUtil.kt, src/test/resources/examples/parameterNameClash/client/HttpUtil.kt, src/test/resources/examples/pathLevelParameters/client/HttpUtil.kt
Fixed client generation when inlined parameter definition specifies an array of integers:
```
openapi: 3.0.1
paths:
/v1/someresource:
delete:
operationId: deleteSomeResource
parameters:
- name: ids
in: query
required: false
schema:
type: array
items:
type: integer
```
Closes #237
=> Fixed query parameters with type List<Int> for OkHttp client

end2end-tests/models-kotlinx/build.gradle.kts, end2end-tests/models-kotlinx/src/test/kotlin/com/cjbooms/fabrikt/models/kotlinx/KotlinxSerializationPrimitiveTypesTest.kt, end2end-tests/models-kotlinx/src/test/resources/primitive_types/content_valid.json, src/main/kotlin/com/cjbooms/fabrikt/generators/PropertyUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/model/JacksonAnnotations.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinTypeInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinxSerializationAnnotations.kt, src/main/kotlin/com/cjbooms/fabrikt/model/SerializationAnnotations.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/KotlinSerializationModelGeneratorTest.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/primitiveTypes/api.yaml, src/test/resources/examples/primitiveTypes/models/Content.kt, src/test/resources/examples/primitiveTypes/models/kotlinx/Content.kt
With Jackson we use Java's BigDecimal for numbers without a format keyword, but because Java types are not serializable with Kotlin Serialization we need to use a Kotlin native type instead. ~~I believe the best we can do is Double although it has lower precision than BigDecimal.~~
Alternatively we could allow the user to provide his own custom serializer for BigDecimal (and other Java types like UUID and URI) as [discussed in this issue](https://github.com/cjbooms/fabrikt/issues/362) by annotating the field with `@Contexual`.
**Update:** 
In order to not loose precision we annotate the field with `@Contexual` and leave it to the user to provide a custom serializer. This is aligns with the [recommended approach](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#seria …
=> Kotlin serialization: Numbers

src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/resources/examples/enumExamples/api.yaml, src/test/resources/examples/enumExamples/models/EnumHolder.kt, src/test/resources/examples/enumExamples/models/NullableEnum.kt
Closes #357
It's simply fixing the NPE that causes the whole generation to fail if an enum has `null` in its list of allowed values, which is how nullable enums should be modeled if done correctly.
Nullable is still in a strange place in OpenAPI per se, since it's completely separate from `required` on the containing object property level. You can actually define some property as `required` even if that property is nullable per it's schema. That would mean that the property key in the JSON would need to be there, but the value could be null. And that is different from the property being completely left out as it would be possible if the property was not `required`. 
The main issue there is that that would be quite hard to model correctly in Kotlin. You would actually need some kind of …
=> Fix correctly defined nullable enums causing a NPE

end2end-tests/ktor/build.gradle.kts, end2end-tests/ktor/src/test/kotlin/com/cjbooms/fabrikt/servers/ktor/InstantDateTimeControllerImpl.kt, end2end-tests/ktor/src/test/kotlin/com/cjbooms/fabrikt/servers/ktor/KtorInstantDateTimeTest.kt, end2end-tests/ktor/src/test/kotlin/com/cjbooms/fabrikt/servers/ktor/KtorQueryParametersTest.kt, end2end-tests/ktor/src/test/kotlin/com/cjbooms/fabrikt/servers/ktor/QueryParametersControllerImpl.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/controller/KtorControllerInterfaceGenerator.kt, src/test/resources/examples/authentication/controllers/ktor/Controllers.kt, src/test/resources/examples/binary/controllers/ktor/Controllers.kt, src/test/resources/examples/byteArrayStream/controllers/ktor/Controllers.kt, src/test/resources/examples/githubApi/controllers/ktor/Controllers.kt, src/test/resources/examples/instantDateTime/api.yaml, src/test/resources/examples/jakartaValidationAnnotations/controllers/ktor/Controllers.kt, src/test/resources/examples/modelSuffix/controllers/ktor/Controllers.kt, src/test/resources/examples/parameterNameClash/controllers/ktor/Controllers.kt, src/test/resources/examples/pathLevelParameters/controllers/ktor/Controllers.kt, src/test/resources/examples/queryParameters/api.yaml, src/test/resources/examples/requestBodyAsArray/controllers/ktor/Controllers.kt, src/test/resources/examples/singleAllOf/controllers/ktor/Controllers.kt
This PR aims to fix #370 
The fix only applies to optional parameter for now on. I would prefer to fix required query params in another PR if you don't mind.
cc @ulrikandersen
=> Handle query params with non primitive type in Ktor controller

src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt, src/test/resources/examples/polymorphicModels/api.yaml, src/test/resources/examples/polymorphicModels/models/Pet.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicSuperType.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicTypeOne.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicTypeOneAnotherRef.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicTypeOneRef.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicTypeTwo.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicTypeTwoRef.kt
Properties of the array type that contain non-inlined objects/enums are not inherited correctly in the current implementation - generic parameter is prefixed with the name of the enclosing class, e.g. instead of `List&lt;Pet&gt;` we have `List&lt;EnclosingTypePet&gt;`
=> Fix inheritance of array properties

build.gradle.kts
Fixes https://github.com/cjbooms/fabrikt/issues/379
Confirmed by building fabrikt and plugin locally, and using the plugin in a build that used to trigger the conflict.
=> relocate old guava libs to prevent conflicts

src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt, src/test/resources/examples/okHttpClient/api.yaml, src/test/resources/examples/okHttpClient/client/ApiClient.kt, src/test/resources/examples/okHttpClient/client/ApiService.kt
In the original implementation, if only 204 No Content and error system responses were defined in the response, the client return value was the model of the error with the response body.
This was considered undesirable behavior, so it has been modified to return Unit if none of the response bodies should be returned in a 2xx.
=> returns Unit when any successful response not exists

README.md
I finally added support for the new String override types from Fabrikt 21.2.
=> Update version of fabrikt-gradle-plugin in README.md

README.md, end2end-tests/spring-http-interface/build.gradle.kts, end2end-tests/spring-http-interface/src/test/kotlin/com/cjbooms/fabrikt/clients/AdditionalQueryParametersTest.kt, settings.gradle.kts, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenOptions.kt, src/main/kotlin/com/cjbooms/fabrikt/cli/CodeGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/OpenFeignInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/SpringHttpInterfaceGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/generators/client/metadata/SpringHttpInterface.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/SpringHttpInterfaceGeneratorTest.kt, src/test/resources/examples/multiMediaType/client/SpringHttpInterfaceClient.kt, src/test/resources/examples/parameterNameClash/client/SpringHttpInterfaceClient.kt, src/test/resources/examples/pathLevelParameters/client/SpringHttpInterfaceClient.kt, src/test/resources/examples/springHttpInterfaceClient/api.yaml, src/test/resources/examples/springHttpInterfaceClient/client/SpringHttpInterfaceClient.kt, src/test/resources/examples/springHttpInterfaceClient/client/SpringHttpInterfaceClientWithResponseEntity.kt, src/test/resources/examples/springHttpInterfaceClient/client/SuspendableSpringHttpInterfaceClient.kt, src/test/resources/examples/springHttpInterfaceClient/models/ClientModels.kt
SpringBoot's HTTP Interface is a declarative http client like Retrofit or OpenFeign.
https://docs.spring.io/spring-framework/reference/integration/rest-clients.html#rest-http-interface
Since SpringBoot has now removed OpenFeign from the official project and seems to be focusing on this HTTP Interface, we thought it reasonable to add support for it and implemented it.
This client supports ResponseEntity and suspend methods, so we move the relevant code to ClientGeneratorUtils and so on.
=> add springboot's http interface generator

src/main/kotlin/com/cjbooms/fabrikt/model/OasType.kt, src/main/kotlin/com/cjbooms/fabrikt/util/YamlUtils.kt
The spec file provided in issue #390 has the following blank type that causes the kaizen parser to crash, so I have added a little function to fix this:
```
Model:
type:
title: Model
```
Also improving the handling of 3.1 nullable definitions, by expanding support to include anyOf definitions. This was a further stumbling block with the API provided in #390
=> Fix NPE on empty type.

src/main/kotlin/com/cjbooms/fabrikt/generators/model/ModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/model/PropertyInfo.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/resources/examples/discriminatedOneOf/api.yaml, src/test/resources/examples/discriminatedOneOf/models/SomeObj.kt, src/test/resources/examples/discriminatedOneOf/models/kotlinx/SomeObj.kt
When dealing with arrays, we must also check that the items schema is inlined before generating a class for it. 
Closes Issue #400
=> Fix issue with inlined oneOf generation under arrays.

src/main/kotlin/com/cjbooms/fabrikt/generators/GeneratorUtils.kt
This should fix the problem mentioned in issue #408. 
It's probably really an issue of bad API definition. But it makes sense for a tool like this to be rather flexible where the spec isn't hard.
=> Fix #408 by doing distinct on body parameters by schema

src/main/kotlin/com/cjbooms/fabrikt/generators/model/ModelGenerator.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/discriminatedOneOf/api.yaml, src/test/resources/examples/discriminatedOneOf/models/SomeObj.kt, src/test/resources/examples/discriminatedOneOf/models/SomeObjInlinedObjectNoMappings.kt, src/test/resources/examples/discriminatedOneOf/models/kotlinx/SomeObj.kt, src/test/resources/examples/discriminatedOneOf/models/kotlinx/SomeObjInlinedObjectNoMappings.kt
Improves robustness of polymorphic code generation for oneOf hierarchies. Add function to resolve discriminator mappings with default fallback. Previously we were not falling back to default behaviour and failing hard.
- Introduced getDiscriminatorMappingsOrDefault to handle oneOf discriminator mappings.
- Supports both explicit mappings and default name-based matching when mappings are absent.
- Logs warnings instead of failing hard if referenced schemas are missing.
Closes #404
=> Fix oneof mappings issue

src/main/kotlin/com/cjbooms/fabrikt/generators/model/ModelGenerator.kt, src/test/resources/examples/enumExamples/api.yaml, src/test/resources/examples/enumExamples/models/EnumObject.kt
Uses [%S format specifier](https://square.github.io/kotlinpoet/s-for-strings/) instead of plain CodeBlock to avoid long enum values being line wrapped.
Fixes #411
=> Support long enum values

src/main/kotlin/com/cjbooms/fabrikt/generators/client/SpringHttpInterfaceGenerator.kt, src/test/resources/examples/multiMediaType/client/SpringHttpInterfaceClient.kt, src/test/resources/examples/parameterNameClash/client/SpringHttpInterfaceClient.kt, src/test/resources/examples/springHttpInterfaceClient/client/SpringHttpInterfaceClient.kt, src/test/resources/examples/springHttpInterfaceClient/client/SpringHttpInterfaceClientWithResponseEntity.kt, src/test/resources/examples/springHttpInterfaceClient/client/SuspendableSpringHttpInterfaceClient.kt
Fixed an issue where the `name` for Kotlin was used for the parameter name of the client generated by SpringBoot Http Client instead of the `originalName`.
I should have realized this when I was writing the test code, sorry.
=> fix SpringBoot http client parameter names

src/main/kotlin/com/cjbooms/fabrikt/util/YamlUtils.kt, src/test/resources/examples/openapi310/api.yaml, src/test/resources/examples/openapi310/models/NewNullableFormat.kt, src/test/resources/examples/openapi310/models/SingleRequiredFieldNullableObject.kt, src/test/resources/examples/requiredReadOnly/api.yaml, src/test/resources/examples/requiredReadOnly/models/RequiredReadOnly.kt
In OAS v3.1 with the `oneOf` syntax, nullable required `$ref` properties were being generated as non-nullable kotlin types. This PR works around the issue by removing the property from the `required` list if it's a nullable ref.
The following openapi
```yaml
openapi: 3.1.0
components:
schemas:
NewNullableFormat:
type: object
required:
- requiredNullableRef
properties:
requiredNullableRef:
oneOf:
- type: 'null'
- $ref: '#/components/schemas/OneObject'
```
will be downgraded to the equivalent OAS 3.0
```yaml
openapi: 3.1.0
components:
schemas:
NewNullableFormat:
type: object
properties:
requiredNullableRef:
$ref: '#/components/schemas/OneObject'
nullable: true  # will be ignored
```
Fixes #424
=> fix: remove property from 'required' if it's a nullable ref

src/main/kotlin/com/cjbooms/fabrikt/generators/client/SpringHttpInterfaceGenerator.kt, src/test/resources/examples/parameterNameClash/client/SpringHttpInterfaceClient.kt, src/test/resources/examples/springHttpInterfaceClient/client/SpringHttpInterfaceClient.kt, src/test/resources/examples/springHttpInterfaceClient/client/SpringHttpInterfaceClientWithResponseEntity.kt, src/test/resources/examples/springHttpInterfaceClient/client/SuspendableSpringHttpInterfaceClient.kt
Fixed a problem where `@PathVariable` argument and `@HttpExchange` argument did not match in name
=> fix spring http interface path param name

src/main/kotlin/com/cjbooms/fabrikt/generators/client/ClientGeneratorUtils.kt, src/main/kotlin/com/cjbooms/fabrikt/model/KotlinGenModels.kt, src/test/resources/examples/okHttpClient/api.yaml, src/test/resources/examples/okHttpClient/client/ApiClient.kt, src/test/resources/examples/okHttpClient/client/ApiService.kt, src/test/resources/examples/okHttpClient/models/ClientModels.kt, src/test/resources/examples/pathLevelParameters/api.yaml, src/test/resources/examples/pathLevelParameters/client/ApiClient.kt, src/test/resources/examples/pathLevelParameters/client/ApiService.kt, src/test/resources/examples/pathLevelParameters/client/OpenFeignClient.kt, src/test/resources/examples/pathLevelParameters/client/SpringHttpInterfaceClient.kt, src/test/resources/examples/pathLevelParameters/controllers/ktor/Controllers.kt, src/test/resources/examples/pathLevelParameters/controllers/micronaut/Controllers.kt, src/test/resources/examples/pathLevelParameters/controllers/spring/Controllers.kt, src/test/resources/examples/pathLevelParameters/models/ClientModels.kt
The Okhttp client code does not compile when a AnyType is used as a header value
=> Change AnyType header to String in generated client code.

src/main/kotlin/com/cjbooms/fabrikt/generators/model/ModelGenerator.kt, src/main/kotlin/com/cjbooms/fabrikt/util/KaizenParserExtensions.kt, src/test/kotlin/com/cjbooms/fabrikt/generators/ModelGeneratorTest.kt, src/test/resources/examples/polymorphicModels/api.yaml, src/test/resources/examples/polymorphicModels/models/PolymorphicType.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicTypeOne.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicTypeOneAnotherRef.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicTypeOneRef.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicTypeTwo.kt, src/test/resources/examples/polymorphicModels/models/PolymorphicTypeTwoRef.kt
When making use of both oneOf and allOf, with sealed interfaces for oneOf, the marker interface for the oneOf was not getting generated.
Cleanup PR extracted to #451 , which should be merged first
=> Fix Missing marker interface for oneOf.
